[package]
authors = ["Stijn"]
edition = "2018"
name = "advent2019"
version = "0.1.0"
[dependencies]
anyhow = "1.0"
arrayvec = "0.5.1"
binary-heap-plus = "0.2.0"
defaultmap = "0.5.0"
float-ord = "0.2"
itertools = "0.8"
ndarray = "0.14.0"
rand = "*"
regex = "1.3"
thiserror = "1.0"
